apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-experiment-step
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-experiment-step
  template:
    metadata:
      labels:
        app: rollout-experiment-step
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:orange
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - experiment:
          duration: 5m
          analyses:
          - name: isd-analysis
            templateName: isd-analysis
            args:
            - name: start-time
              value: "{{experiment.availableAt}}"
          templates:
          - name: baseline
            specRef: baseline
          - name: canary
            specRef: canary
