kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis-nr
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: isd-analysis-score
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: nrcustom
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: service1
            metricScopeVariables: "${host_key}"
            baselineMetricScope: "nr-isd-rollout-{{args.baseline-hash}}-.*" 
            canaryMetricScope: "nr-isd-rollout-{{args.canary-hash}}-.*"
            metricTemplateName: newrelict1
