kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis-nr
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: isd-analysis-score
      count: 1
      initialDelay: 2s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          baselineStartTime: "2022-09-19T14:00:00Z"
          canaryStartTime: "2022-09-19T14:00:00Z"
          application: isd-for-nr-canary
          user: admin
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: testtemplatefornr2
            metricScopeVariables: "resource.labels.container_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-br"
