kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis-nr
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: isd-analysis-score
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: newrelic
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: service1
            gateName: gate1
            metricScopeVariables: "host.displayName"
            baselineMetricScope: ".*{{args.baseline-hash}}.*" 
            canaryMetricScope: ".*{{args.canary-hash}}.*"
