apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      trafficRouting:
        nginx:
          stableIngress: canary-demo-ingress 
      steps:
      - setWeight: 5
      - pause: {}
      - analysis:
          templates:
            - templateName: canary-isd-analysis
          args:
            - name: canary-hash
              valueFrom:
                podTemplateHashValue: Latest
            - name: baseline-hash
              valueFrom:
                podTemplateHashValue: Stable      
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - name: canary-demo
        image: argoproj/rollouts-demo:yellow
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
