apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-canary-v2
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-demo

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-stable-v1
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-demo
