apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: multiservice
spec:
  metrics:
    - name: multiservice
      provider:
        opsmx:
          gate_url: https://ds312.isd-dev.opsmx.net/
          application: multiservice
          canary_start_time:   "2022-08-10T13:15:00Z"
          baseline_start_time:   "2022-08-10T13:15:00Z"
          lifetimeHours: "0.5"
          threshold:
            pass: 80
            marginal: 60
          services:
          - servicename: "service2"
            gatename: "gate2"
            MetricScopeVariables: "${namespace_key},${pod_key},${app_name},${component_name}"
            BaselineMetricScope: "baseline,oes-gate,oes,autopilot"
            CanaryMetricScope: "canary,oes-gate,oes,autopilot"
