apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: multiservice
spec:
  metrics:
    - name: multiservice
      provider:
        opsmx:
          user: admin
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: multiservice
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
