apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analysis-isd
spec:
  args:
  - name: start-time
  - name: end-time
  metrics:
    - name: analysis-isd
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: demoapp
          user: admin
          baselineStartTime: "2022-08-20T13:15:00Z"
          canaryStartTime: "2022-08-20T13:15:00Z"
          endTime: "2022-08-20T13:45:00Z"
          threshold:
            pass: 80
            marginal: 60
