apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: multiservice
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: multiservice
      provider:
        opsmx:
          user: admin
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: multiservice
          baselineStartTime: "2022-08-02T12:15:00Z"
          canaryStartTime: "2022-08-02T12:15:00Z"
          lifetimeHours: "0.5"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: service1
            gateName: gate1
            metricScopeVariables: "job_name"
            baselineMetricScope: ".*{{args.experiment-hash}}.*baseline.*" 
            canaryMetricScope: ".*{{args.experiment-hash}}.*canary.*"
