apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: oes-analysis-isd
spec:
  args:
  - name: start-time
  - name: end-time
  metrics:
    - name: oes-analysis-isd
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          user: "admin"
          application: testapp
          baselineStartTime: "2022-09-05T13:15:00Z"
          canaryStartTime: "2022-09-05T13:15:00Z"
          endTime: "2022-09-05T13:45:00Z"
          threshold:
            pass: 80
            marginal: 60
