apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: multiservice
spec:
  metrics:
    - name: multiservice
      provider:
        opsmx:
          user: admin
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: testapp
          baselineStartTime: "2022-08-02T12:15:00Z"
          canaryStartTime: "2022-08-02T12:15:00Z"
          lifetimeHours: "0.5"
          threshold:
            pass: 80
            marginal: 60
