apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analysis-isd
spec:
  args:
  - name: start-time
  - name: end-time
  metrics:
    - name: analysis-isd
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: multiservice
          user: admin
          lifetimeHours: '0.05'
          globalLogTemplate: logverification
          threshold:
            pass: 80
            marginal: 60
          services:
            - logTemplateName: logtemp
              logScopeVariables: kubernetes.pod_name
              baselineLogScope: '.*{{args.experiment-hash}}.*baseline.*'
              canaryLogScope: '.*{{args.experiment-hash}}.*canary.*'
              metricTemplateName: metrictemplate
              metricScopeVariables: 'namespace_key,pod_key'
              baselineMetricScope: 'argocd,.*{{args.experiment-hash}}.*baseline.*'
              canaryMetricScope: 'argocd,.*{{args.experiment-hash}}.*canary.*'
