apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analysis-isd
spec:
  args:
  - name: start-time
  - name: end-time
  metrics:
    - name: analysis-isd
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: junaidexp
          user: admin
          lifetimeHours: '0.05'
          globalLogTemplate: logverification
          threshold:
            pass: 80
            marginal: 60
          services:
            - serviceName: service1
              logTemplateName: logtemp
              logScopeVariables: kubernetes.container_name
              baselineLogScope: 'oes-datascience-br'
              canaryLogScope: 'oes-datascience-cr'
              metricTemplateName: metrictemplate
              metricScopeVariables: 'job_name'
              baselineMetricScope: 'oes-platform-br'
              canaryMetricScope: 'oes-platform-cr'
