apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analysis-isd
spec:
  args:
  - name: start-time
  - name: end-time
  - name: baseline-hash
  - name: canary-hash
  metrics:
    - name: analysis-isd
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: junaidexp
          user: admin
          lifetimeHours: '0.05'
          globalLogTemplate: logverification
          threshold:
            pass: 80
            marginal: 60
          services:
            - logTemplateName: logtemp
              logScopeVariables: kubernetes.container_name
              baselineLogScope: '.*{{args.baseline-hash}}.*'
              canaryLogScope: '.*{{args.canary-hash}}.*'
              metricTemplateName: prometheusverificationv41
              metricScopeVariables: 'namespace_key,pod_key'
              baselineMetricScope: 'argocd,.*{{args.baseline-hash}}.*'
              canaryMetricScope: 'argocd,.*{{args.canary-hash}}.*'
