apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: multiservice
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          user: admin
          application: multiservice
          baselineStartTime: "2022-08-20T13:15:00Z"
          canaryStartTime: "2022-08-20T13:15:00Z"
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: "service1"
            gateName: "gate1"
            metricTemplateName: "metrictemplate"
            metricScopeVariables: "job_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-cr"
            logTemplateName: "logtemp"
            logScopeVariables: "job_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"
