apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        isd:
          gate_url: https://ds312.isd-dev.opsmx.net/
          application: testapp
          baseline_start_time: "2022-08-02T12:15:00Z"
          canary_start_time: "2022-08-02T12:15:00Z"
          end_time: "2022-08-02T13:15:10Z"
          threshold:
            pass: 80
            marginal: 60
