kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: custommetric
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: custommetric
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          baselineStartTime: "2022-09-19T08:30:00Z"
          canaryStartTime: "2022-09-19T08:30:00Z"
          application: demonewrelic
          user: admin
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: newrelictemplate
            metricScopeVariables: "resource.labels.container_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-br"
            metricTemplateVersion: "v9.0"
