apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: oes-argo-rollout
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo-exp-2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus_io_path: '/mgmt/prometheus'
        prometheus_io_port: '8088'    
      labels:
        app: rollouts-demo-exp-2
    spec:
      containers:
        - name: rollouts-baseline
          image: quay.io/opsmxpublic/canary-issuegen:issue-canary-gen-1325
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - experiment:
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analyses:
              - name : oes-analysis
                requiredForCompletion: true
                templateName: oes-analysis
                args:
                  - name: baseline-hash
                    value: "{{templates.baseline.podTemplateHash}}"                   
                  - name: canary-hash
                    value: "{{templates.canary.podTemplateHash}}"
        - setWeight: 60
        - pause: { duration: 30s }
        - setWeight: 80
        - pause: { duration: 30s }
        - setWeight: 100
