kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: oes-analysis
      count: 1
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: demoapphash
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - servicename: service1
            gatename: gate1
            metricScopeVariables: "job_name"
            baselineMetricScope: ".*{{args.baseline-hash}}.*" 
            canaryMetricScope: ".*{{args.canary-hash}}.*"                         
