apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: multiservice-analysis-v2
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: multiservice-analysis-v2
      initialDelay: "60s"
      provider:
        opsmx:
          user: admin
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: demomultiserviceapp
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: "service1"
            gateName: "gate1"
            metricScopeVariables: "namespace_key,pod_key"
            baselineMetricScope: "argocd,.*{{args.experiment-hash}}.*baseline.*"
            canaryMetricScope: "argocd,.*{{args.experiment-hash}}.*canary.*"
          - serviceName: "service2"
            gateName: "gate2"
            metricScopeVariables: "namespace_key,pod_key"
            baselineMetricScope: "argocd,.*{{args.experiment-hash}}.*baseline.*"
            canaryMetricScope: "argocd,.*{{args.experiment-hash}}.*canary.*"
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "oes-datascience"
            canaryLogScope: "oes-datascience"
