apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          gate_url: https://ds312.isd-dev.opsmx.net/
          application: testapp
          canary_start_time:   "2022-08-10T13:15:00Z"
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          - servicename: "service1"
            gatename: "gate1"
            MetricScopeVariables: "${namespace_key},${pod_key},${app_name},${component_name}"
            BaselineMetricScope: "baseline,oes-gate,oes,autopilot"
            CanaryMetricScope: "canary,oes-gate,oes,autopilot"
