apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          user: admin
          application: testapp
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
