apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          user: admin
          application: junaid-test
          baselineStartTime: "2022-08-20T13:15:00Z"
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricScopeVariables: "job_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-cr"
            metricTemplateName: PrometheusMetricTemplate
