apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          user: admin
          application: multiservice
          baselineStartTime: "2022-08-20T13:15:00Z"
          lifetimeHours: "0.5"
          threshold:
            pass: 80
            marginal: 60
          services:
          - servicename: "service1"
            gatename: "gate1"
            metricScopeVariables: "job_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-cr"
            LogScopeVariables: "kubernetes.container_name"
            BaselineLogScope: "oes-datascience-br"
            CanaryLogScope: "oes-datascience-cr"
