kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: demo-isd-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: demo-isd-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: demo-test
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: logverification
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            metricTemplateName: prometheusverificationv41
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "argocd,{{args.baseline-hash}}"
            canaryMetricScope: "argocd,{{args.canary-hash}}"
