apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: testapp-runexp-isd
spec:
  duration: 3m
  templates:
  - name: green
    selector:
      matchLabels:
        app: rollouts-demo-exp-2
    template:
      metadata:
        labels:
          app: rollouts-demo-exp-2
      spec:
        containers:
        - name: baseline
          image: quay.io/opsmxpublic/canary-issuegen:issue-canary-gen-1325
          imagePullPolicy: Always
  - name: orange
    selector:
      matchLabels:
        app: rollouts-demo-exp-2
    template:
      metadata:
        labels:
          app: rollouts-demo-exp-2
      spec:
        containers:
        - name: canary
          image: quay.io/opsmxpublic/canary-issuegen:issue-canary-gen-1326
          imagePullPolicy: Always
  analyses:
  - name: isd-analysis
    requiredForCompletion: true
    templateName: isd-analysis
    args:
    - name: baseline-hash
      value: "{{templates.green.podTemplateHash}}"
    - name: canary-hash
      value: "{{templates.orange.podTemplateHash}}"
