kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: isd-analysis-score
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: issuegenapp-canary
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: demoserviceforisd
            metricScopeVariables: "resource.labels.container_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-br"
            metricTemplateName: newrelictemplate
