kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: isd-analysis-score
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          gateUrl: https://argoisdqa.isd-dev.opsmx.net/
          application: sep22application
          user: admin
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: logverification
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            metricTemplateName: nranalysisv4
            metricScopeVariables: "app_key,pod_key"
            baselineMetricScope: "demo-test,{{args.baseline-hash}}"
            canaryMetricScope: "demo-test,{{args.canary-hash}}"
