kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: isd-analysis-score
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: issuegenapp-canary
          user: admin
          baselineStartTime: "2022-09-16T06:10:00Z"
          canaryStartTime: "2022-09-19T08:06:00Z"
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: stackdriverlog
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: issuegen-prod
            canaryLogScope: issuegen-prod
