apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        isd:
          gate_url: https://ds312.isd-dev.opsmx.net/
          baseline_start_time: "2022-08-08T12:15:00Z"
          application: testapp
          threshold:
            pass: 60
            marginal: 80
