kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: qa-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: qa-analysis
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: metricanalysisapp
          user: admin
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: metricsvcbyqa
            metricTemplateName: qametrictemp
            metricScopeVariables: "resource.labels.container_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-br
            
