kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: qa-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: qa-analysis
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://argoisdqa.isd-dev.opsmx.net//
          application: metricanalysisapp
          user: admin
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: metricsvcbyqa
            metricTemplateName: CUSTOMPrometheus
            metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,.*{{args.baseline-hash}}.*,issuegenapp-canary"
            canaryMetricScope: "argocd,.*{{args.canary-hash}}.*,issuegenapp-canary"
            
