apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: expend
spec:
  duration: 10m
  templates:
  - name: green
    selector:
      matchLabels:
        app: rollouts-demo-exp-2
    template:
      metadata:
        labels:
          app: rollouts-demo-exp-2
      spec:
        containers:
        - name: rollouts-demo-exp
          image: docker.io/opsmxdev/issuegen:v3.0.6
          imagePullPolicy: Always
  - name: orange
    selector:
      matchLabels:
        app: rollouts-demo-exp-2
    template:
      metadata:
        labels:
          app: rollouts-demo-exp-2
      spec:
        containers:
        - name: rollouts-demo-exp
          image: docker.io/opsmxdev/issuegen:v3.0.8
          imagePullPolicy: Always
  analyses:
  - name: testapp
    templateName: testapp
    args:
    - name: start-time
      value: "{{experiment.availableAt}}"
    - name: end-time
      value: "{{experiment.finishedAt}}"
