apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: expend
spec:
  duration: 10m
  template:
    metadata:
      labels:
        app: expend
    spec:
      containers:
      - name: rollouts-demo
        image: docker.io/opsmxdev/issuegen:v3.0.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  analyses:
  - name: testapp
    templateName: testapp
    args:
    - name: start-time
      value: "{{experiment.availableAt}}"
    - name: end-time
      value: "{{experiment.finishedAt}}"
